<font color = 'Purple'  size = 3>
    
# 01 - Tensores con Pytorch

Importamos las librerías de utilidad.

In [1]:
import torch 
import numpy as np
import pandas as pd

In [2]:
# Versión de torch. 
torch.__version__

'1.7.1'

En una matriz, la primer entrada indica el número de filas y la segunda entrada el número de columnas. 

En un tensor la primer entrada será el número de vectores ("filas") y la segunda entrada es el número de valores que tendrá cada vector ("columnas").

In [3]:
# Generar un tensor de n vectores con m unos en cada vector. 
n = 6
m = 5
tensor_a = torch.ones(n,m)
tensor_a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [4]:
# Matriz de 6 x 8 llena de unos.
unos_matriz = np.ones((6, 5))
unos_matriz

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
print('Dimensión de unos_matriz: ', unos_matriz.ndim)
print('Dimensión de tensor_a:    ', tensor_a.ndim)

Dimensión de unos_matriz:  2
Dimensión de tensor_a:     2


Al trabajar con pytorch es importante reconocer la forma en que se define un tensor pues si usamos numpy podemos obtener el mismo arreglo y éste es tratado como una matriz y no como un tensor. Esto es importante al momento de hacer operaciones entre arreglos donde las dimensiones del arreglo deben de ser las adecuadas para que se puedan efectuar las operaciones.

Generemos ahora un tensor con valores aleatorios:

In [6]:
# Tensor con valores aleatorios:
tensor_b = torch.Tensor(5,6)         # Usamos 'Tensor' para generar el tensor aleatorio (Notar que 'Tensor' es con 'T').
print('Tensor con valores aleatorios: \n ', tensor_b)

# El tensor anterior se puede modificar de manera que los valores ahora esten entre 0 y 1.
tensor_b = tensor_b.uniform_(0,1)    # Para esta acción usamos 'uniform' e indicando entre que números van a estar los datos.
print('\n Tensor modificado ahora con valores entre 0 y 1: \n ', tensor_b)               

Tensor con valores aleatorios: 
  tensor([[8.4490e-39, 9.6429e-39, 9.2755e-39, 1.0286e-38, 9.0919e-39, 8.9082e-39],
        [9.2755e-39, 8.4490e-39, 8.9082e-39, 9.1837e-39, 1.0561e-38, 8.7245e-39],
        [9.6429e-39, 1.0561e-38, 9.7347e-39, 1.0194e-38, 4.2246e-39, 1.0286e-38],
        [5.0510e-39, 1.0928e-38, 1.0102e-38, 8.9082e-39, 9.1837e-39, 4.7755e-39],
        [1.0286e-38, 9.1837e-39, 4.5918e-39, 6.1530e-39, 1.0102e-38, 9.6429e-39]])

 Tensor modificado ahora con valores entre 0 y 1: 
  tensor([[0.5247, 0.7088, 0.8859, 0.3214, 0.8524, 0.4579],
        [0.6821, 0.8514, 0.2578, 0.2957, 0.0691, 0.3238],
        [0.2628, 0.4352, 0.3889, 0.7120, 0.0744, 0.2754],
        [0.7336, 0.7920, 0.4537, 0.5767, 0.3024, 0.3188],
        [0.4602, 0.7942, 0.4785, 0.4551, 0.2470, 0.5354]])


Por otro lado, se puede generar un tensor con valores aleatorios entre 0 y 1 usando 'rand'.

In [7]:
tensor_c = torch.rand(5,6)
tensor_c

tensor([[0.5165, 0.9067, 0.3144, 0.5992, 0.1637, 0.9709],
        [0.9526, 0.7855, 0.3082, 0.8366, 0.6865, 0.6184],
        [0.2563, 0.4076, 0.8285, 0.5078, 0.7854, 0.9720],
        [0.8931, 0.9759, 0.3501, 0.9275, 0.1307, 0.9538],
        [0.2465, 0.9884, 0.4787, 0.0511, 0.4070, 0.1482]])

Los tensores se pueden sumar, la suma es entrada a entrada por ello es importante que las dimensiones de los tensores sean iguales.

In [8]:
suma_tensores = tensor_b + tensor_c
suma_tensores

tensor([[1.0412, 1.6155, 1.2003, 0.9206, 1.0162, 1.4288],
        [1.6347, 1.6369, 0.5660, 1.1323, 0.7556, 0.9422],
        [0.5190, 0.8428, 1.2174, 1.2197, 0.8599, 1.2473],
        [1.6267, 1.7679, 0.8038, 1.5042, 0.4331, 1.2726],
        [0.7066, 1.7825, 0.9572, 0.5062, 0.6540, 0.6836]])

Se pueden cambiar las dimensiones de los tensores.

In [9]:
print(suma_tensores.shape)                      # Muestra la forma del tensor suma.
tensor_convertido = suma_tensores.view(6, 5)    # Convierte el tensor suma de dimensiones (5,6) a uno de dimenisones (6,5).
print(tensor_convertido)
print(tensor_convertido.shape)

torch.Size([5, 6])
tensor([[1.0412, 1.6155, 1.2003, 0.9206, 1.0162],
        [1.4288, 1.6347, 1.6369, 0.5660, 1.1323],
        [0.7556, 0.9422, 0.5190, 0.8428, 1.2174],
        [1.2197, 0.8599, 1.2473, 1.6267, 1.7679],
        [0.8038, 1.5042, 0.4331, 1.2726, 0.7066],
        [1.7825, 0.9572, 0.5062, 0.6540, 0.6836]])
torch.Size([6, 5])


Se pueden cambiar los valores de las entradas de los tensores.

In [31]:
tensor = torch.tensor([[1.0,2.0],[3.0,4.0]])  # Genera un tensor con las entradas que deseemos.
print(tensor)
tensor[0][1] = 2.5                            # Modifica la entrada (0,1) del tensor.
print(tensor)
tensor.storage()                              # Muestra los valores almacenados en el tensor.

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])


 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

In [32]:
tensor, tensor.stride()                       # Revisar la función .stride().

(tensor([[1.0000, 2.5000],
         [3.0000, 4.0000]]),
 (2, 1))

In [12]:
tensor_t = tensor.t()                         # Es el tensor transpuesto al tensor anterior.
tensor_t, tensor_t.stride()

(tensor([[1.0000, 3.0000],
         [2.5000, 4.0000]]),
 (1, 2))

In [39]:
tensor_x = torch.tensor([1,2,3,4])            # Se genera un tensor de una dimensión.
tensor_x, torch.unsqueeze(tensor_x, 0)        # Cambia la dimensión del tensor.

(tensor([1, 2, 3, 4]), tensor([[1, 2, 3, 4]]))

In [14]:
tensor_x, torch.unsqueeze(tensor_x, 1)        # Cambia la dimensión del tensor. 

(tensor([1, 2, 3, 4]),
 tensor([[1],
         [2],
         [3],
         [4]]))

Los arreglos generados con Numpy se puede transformar en tensores usando torch.

In [42]:
arreglo = np.random.randn(3,3)                # Genera un arreglo de n x n usando numpy.
print(arreglo)
tensor_arreglo = torch.from_numpy(arreglo)    # El arreglo generado con numpy, torch lo vuelve un tensor.
tensor_arreglo

[[ 0.30751544  0.18480727 -1.63485123]
 [-0.79259278  0.63457667  0.69178408]
 [ 0.55144208  0.46556796 -1.01254989]]


tensor([[ 0.3075,  0.1848, -1.6349],
        [-0.7926,  0.6346,  0.6918],
        [ 0.5514,  0.4656, -1.0125]], dtype=torch.float64)

Se puede obtener información estadística de las cantidades que hay en los tensores.

In [44]:
print(tensor_arreglo)
print(torch.mean(tensor_arreglo))             # Tensor con la media de todos los valores en el tensor.
print(torch.mean(tensor_arreglo, dim = 0))    # Tensor con la media de los valores que se encuantran por columna.
print(torch.mean(tensor_arreglo, dim = 1))    # Tensor con la media de los valores que se encuantran en la fila.

tensor([[ 0.3075,  0.1848, -1.6349],
        [-0.7926,  0.6346,  0.6918],
        [ 0.5514,  0.4656, -1.0125]], dtype=torch.float64)
tensor(-0.0671, dtype=torch.float64)
tensor([ 0.0221,  0.4283, -0.6519], dtype=torch.float64)
tensor([-0.3808,  0.1779,  0.0015], dtype=torch.float64)


In [47]:
print(tensor_arreglo)
print(torch.std(tensor_arreglo))              # Tensor con la desviación estándar de todos los valores en el tensor.
print(torch.std(tensor_arreglo, dim = 0))     # Tensor con la desviación estándar de los valores que se encuantran por columna.
print(torch.std(tensor_arreglo, dim = 1))     # Tensor con la desviación estándar de los valores que se encuantran en la fila.

tensor([[ 0.3075,  0.1848, -1.6349],
        [-0.7926,  0.6346,  0.6918],
        [ 0.5514,  0.4656, -1.0125]], dtype=torch.float64)
tensor(0.8527, dtype=torch.float64)
tensor([0.7160, 0.2272, 1.2045], dtype=torch.float64)
tensor([1.0877, 0.8410, 0.8792], dtype=torch.float64)


<font color = 'Purple'  size = 2>
    
# Representar datos con tensores

Vamos a cargar un conjunto de datos sobre fútbol en un 'data frame' usando Pandas.

In [68]:
url = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv" 
dataframe = pd.read_csv(url)       # Con pandas se lee el archivo csv y se guarda en una variable.
dataframe

Unnamed: 0      ID                Name  Age  \
0               0  158023            L. Messi   31   
1               1   20801   Cristiano Ronaldo   33   
2               2  190871           Neymar Jr   26   
3               3  193080              De Gea   27   
4               4  192985        K. De Bruyne   27   
...           ...     ...                 ...  ...   
18202       18202  238813        J. Lundstram   19   
18203       18203  243165  N. Christoffersson   19   
18204       18204  241638           B. Worman   16   
18205       18205  246268      D. Walker-Rice   17   
18206       18206  246269           G. Nugent   16   

                                                Photo Nationality  \
0      https://cdn.sofifa.org/players/4/19/158023.png   Argentina   
1       https://cdn.sofifa.org/players/4/19/20801.png    Portugal   
2      https://cdn.sofifa.org/players/4/19/190871.png      Brazil   
3      https://cdn.sofifa.org/players/4/19/193080.png       Spain   
4      https://cdn.sofifa.org/players/4/19/192985.png     Belgium   
...                                               ...         ...   
18202  https://cdn.sofifa.org/players/4/19/238813.png     England   
18203  https://cdn.sofifa.org/players/4/19/243165.png      Sweden   
18204  https://cdn.sofifa.org/players/4/19/241638.png     England   
18205  https://cdn.sofifa.org/players/4/19/246268.png     England   
18206  https://cdn.sofifa.org/players/4/19/246269.png     England   

                                      Flag  Overall  Potential  \
0      https://cdn.sofifa.org/flags/52.png       94         94   
1      https://cdn.sofifa.org/flags/38.png       94         94   
2      https://cdn.sofifa.org/flags/54.png       92         93   
3      https://cdn.sofifa.org/flags/45.png       91         93   
4       https://cdn.sofifa.org/flags/7.png       91         92   
...                                    ...      ...        ...   
18202  https://cdn.sofifa.org/flags/14.png       47         65   
18203  https://cdn.sofifa.org/flags/46.png       47         63   
18204  https://cdn.sofifa.org/flags/14.png       47         67   
18205  https://cdn.sofifa.org/flags/14.png       47         66   
18206  https://cdn.sofifa.org/flags/14.png       46         66   

                      Club  ... Composure Marking StandingTackle  \
0             FC Barcelona  ...      96.0    33.0           28.0   
1                 Juventus  ...      95.0    28.0           31.0   
2      Paris Saint-Germain  ...      94.0    27.0           24.0   
3        Manchester United  ...      68.0    15.0           21.0   
4          Manchester City  ...      88.0    68.0           58.0   
...                    ...  ...       ...     ...            ...   
18202      Crewe Alexandra  ...      45.0    40.0           48.0   
18203       Trelleborgs FF  ...      42.0    22.0           15.0   
18204     Cambridge United  ...      41.0    32.0           13.0   
18205      Tranmere Rovers  ...      46.0    20.0           25.0   
18206      Tranmere Rovers  ...      43.0    40.0           43.0   

       SlidingTackle GKDiving  GKHandling  GKKicking  GKPositioning  \
0               26.0      6.0        11.0       15.0           14.0   
1               23.0      7.0        11.0       15.0           14.0   
2               33.0      9.0         9.0       15.0           15.0   
3               13.0     90.0        85.0       87.0           88.0   
4               51.0     15.0        13.0        5.0           10.0   
...              ...      ...         ...        ...            ...   
18202           47.0     10.0        13.0        7.0            8.0   
18203           19.0     10.0         9.0        9.0            5.0   
18204           11.0      6.0         5.0       10.0            6.0   
18205           27.0     14.0         6.0       14.0            8.0   
18206           50.0     10.0        15.0        9.0           12.0   

      GKReflexes Release Clause  
0            8.0        €226.5M 

In [69]:
# Muestra el nombre de los encabezados de las columnas en el conjunto de datos.
dataframe.columns   

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [70]:
# Consideramos sólo algunas columnas del conjunto de datos las cuales continen valores numéricos.
subset = dataframe[['Overall', 'Age', 'International Reputation', 'Weak Foot', 'Skill Moves' ]].dropna(axis = 0, how = "any") 

# Eliminamos el encabezado de las columnas que elegimos.
columns = subset.columns[1:]   
players = torch.tensor(subset.values).float()  # Muestra los valores de la columnas elegidas.
print(players)
players.shape, players.type()                  # Muestra la forma del tensor y el tipo de elementos que contiene.

tensor([[94., 31.,  5.,  4.,  4.],
        [94., 33.,  5.,  4.,  5.],
        [92., 26.,  5.,  5.,  5.],
        ...,
        [47., 16.,  1.,  3.,  2.],
        [47., 17.,  1.,  3.,  2.],
        [46., 16.,  1.,  3.,  2.]])


(torch.Size([18159, 5]), 'torch.FloatTensor')

In [71]:
# Eliminamos la primer columna correspondiente al 'Overall'
data = players[:, 1:]   
data, data.shape

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]),
 torch.Size([18159, 4]))

In [72]:
# Ahora mostramos la columna correspondiente al 'Overall'
target = players[:, 0]  
target, target.shape

(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

In [74]:
# Se calcula la media y la desviación estándar de las columnas de 'data'.
mean = torch.mean(data, dim = 0)
print('Media:      ', mean)
std = torch.std(data, dim = 0)
print('Desviación: ', std)

Media:       tensor([25.1225,  1.1132,  2.9473,  2.3613])
Desviación:  tensor([4.6706, 0.3940, 0.6605, 0.7562])


In [75]:
# Normalización de los datos.
norm = (data - mean)/torch.sqrt(std)
norm

tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

In [76]:
# Dividir los grupos a analizar.
good = data[torch.ge(target, 85)]                               # Los jugadores buenos tienen un target mayor a 85.
average = data[torch.gt(target, 70) & torch.lt(target, 85)]     # Los jugadores promedio tienen un target entre 70 y 85.
notSoGood = data[torch.le(target, 70)]                          # Los jugadores no tan buenos tienen un target menor a 70.

# Cálculo del promedio de los resultados anteriores.
goodMean = torch. mean(good, dim = 0)
averageMean = torch. mean(average, dim = 0)
notSoGoodMean = torch. mean(notSoGood, dim = 0)
 
# Mostrar los tensores.
goodMean, averageMean, notSoGoodMean

(tensor([28.3455,  3.3818,  3.4455,  3.0364]),
 tensor([27.2285,  1.3561,  3.1114,  2.7515]),
 tensor([24.3676,  1.0106,  2.8864,  2.2208]))

In [77]:
# Imprimimos en un mejor formato los resultados obtenidos.
for i, args in enumerate(zip(columns, goodMean, averageMean, notSoGoodMean)):
  print("{:25} {:6.2f} {:6.2f} {:6.2f}".format(*args))

Age                        28.35  27.23  24.37
International Reputation    3.38   1.36   1.01
Weak Foot                   3.45   3.11   2.89
Skill Moves                 3.04   2.75   2.22
