<font color = 'purple'  size = 3>
    
# Fundamentos Prácticos de Machine Learning
    
# 01 - Introducción a Numpy

#### Importamos Numpy

In [1]:
import numpy as np

#### Creamos un 'array'. Podemos entender a un 'array' como un arreglo unidimensional, es decir, un vector.

In [2]:
np.array([10, 20, 24, 5, 15, 50])

array([10, 20, 24,  5, 15, 50])

#### Podemos tomar un valor en el arreglo, recordando que la cuenta inicia en cero.

In [3]:
a = np.array([10, 30, 20, 4, 75, 51, 7, 2, 4, 40, 100])
a[4]

75

#### Podemos tomar valores en el arreglo dentro de un rango

In [4]:
# Del índice 3 hasta el final.
a[3:]

array([  4,  75,  51,   7,   2,   4,  40, 100])

In [5]:
# Del índice 3 hasta el índice 7.
a[3:7]

array([ 4, 75, 51,  7])

In [6]:
# Del índice 1 hasta el final pero en pasos de 2.
a[1::2]

array([30,  4, 51,  2, 40])

#### Podemos crear una arreglo de tamaño $n$ lleno de ceros.

In [7]:
# Tomamos n = 10.
ceros = np.zeros(10)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Lo mismo podemos hacer con un arreglo lleno de unos.

In [8]:
# Tomamos n = 10.
unos = np.ones(10)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Podemos entender el arreglo de ceros y unos a arreglos de dos dimensiones, es decir, matrices de $n x m$

In [9]:
# Matriz de 7 x 9 llena de ceros.
ceros_matriz = np.zeros((7, 9))
ceros_matriz

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
# Matriz de 6 x 8 llena de unos.
unos_matriz = np.ones((6, 8))
unos_matriz

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
print(type(unos))           
print(type(ceros))
print(type(unos_matriz))
print(type(unos_matriz))
print(type(unos[3]))
print(type(unos_matriz[3,3]))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
<class 'numpy.float64'>


#### Podemos crear un arreglo con números entre dos valores cada uno con la misma cantidad de diferencia entre sí.

In [12]:
# 10 Números entre 5 y 50 con la misma cantidad de diferencia entre ellos. 
np.linspace(5, 50, 10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

#### Podemos crear arreglos no sólo con números.

In [13]:
arreglo = np.array( [['x', 'y', 'z'], ['a', 'c', 'e']])
print(arreglo)
type(arreglo)

[['x' 'y' 'z']
 ['a' 'c' 'e']]


numpy.ndarray

In [14]:
# Usamos 'ndim' para conocer la dimensión del arreglo. 
arreglo.ndim

2

#### Usando 'sort' podemos ordenar un arreglo númerico en orden ascendente.

In [15]:
arreglo_num = [12, 4, 10, 40, 2, 5, 97, 63, 82, 73, 35, 28, 83, 19]
np.sort(arreglo_num)

array([ 2,  4,  5, 10, 12, 19, 28, 35, 40, 63, 73, 82, 83, 97])

#### También podemos usar 'sort' en arreglos más complejos.

In [16]:
cabeceras = [ ('nombre', 'S10' ), ('edad', int) ]
datos = [ ('Juan', 10), ('Maria', 70), ('Javier', 42), ('Samuel', 15) ]
usuarios = np.array(datos, dtype = cabeceras)
print('Arreglo original:           ', usuarios)

orden = np.sort(usuarios, order = 'edad' )
print('Arreglo ordenado por edad:  ', orden)

Arreglo original:            [(b'Juan', 10) (b'Maria', 70) (b'Javier', 42) (b'Samuel', 15)]
Arreglo ordenado por edad:   [(b'Juan', 10) (b'Samuel', 15) (b'Javier', 42) (b'Maria', 70)]


#### Con 'arange' podemos crear un arreglo con números naturales según la cantidad que indiquemos.

In [17]:
# Arreglo con 51 números, comenzando en cero.
np.arange(51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [18]:
# Arreglo con números naturales pero en un rango entre 10 y 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [19]:
# Números entre 5 y 51 pero en pasos de 5.
np.arange(5, 51, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

#### Es posible crear arreglos de $n x m$ no sólo con ceros y unos sino que con cualquier número, usando 'full'.

In [20]:
a = np.full( (6, 8), 8)
b = np.full((4, 6), 10)
print(a)
print(b)

[[8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]]
[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


#### Podemos crear matrices diagonales con 'diag'.

In [21]:
np.diag ( [1, 3, 9, 10, 6, 8] )

array([[ 1,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0],
       [ 0,  0,  9,  0,  0,  0],
       [ 0,  0,  0, 10,  0,  0],
       [ 0,  0,  0,  0,  6,  0],
       [ 0,  0,  0,  0,  0,  8]])