<font color = 'purple'  size = 3>
    
# Introducción a Numpy

#### Importamos Numpy

In [1]:
import numpy as np

#### Creamos un 'array'. Podemos entender a un 'array' como un arreglo unidimensional, es decir, un vector.

In [2]:
arreglo = np.array([10, 20, 24, 5, 15, 50])
arreglo

array([10, 20, 24,  5, 15, 50])

#### Otra forma de crear un 'array' es transformando una lista .

In [3]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
array = np.array(lista)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Si usamos 'print' para imprimir un arreglo omitirá la palabra 'array' y sólo tendremos al arreglo en su correspondinte dimensión.

In [4]:
print (arreglo)
print ('--------------------------------')
print (array)

[10 20 24  5 15 50]
--------------------------------
[ 1  2  3  4  5  6  7  8  9 10]


#### Podemos tomar un valor en el arreglo, recordando que la cuenta inicia en cero.

In [5]:
a = np.array([10, 30, 20, 4, 75, 51, 7, 2, 4, 40, 100])
a[4]

75

#### Podemos tomar valores en el arreglo dentro de un rango

In [6]:
# Del índice 3 hasta el final.
a[3:]

array([  4,  75,  51,   7,   2,   4,  40, 100])

In [7]:
# Del índice 3 hasta el índice 7.
a[3:7]

array([ 4, 75, 51,  7])

In [8]:
# Del índice 1 hasta el final pero en pasos de 2.
a[1::2]

array([30,  4, 51,  2, 40])

#### Podemos crear una arreglo de tamaño $n$ lleno de ceros.

In [9]:
# Tomamos n = 10.
ceros = np.zeros(10)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### También podemos crear un arreglo con ceros usando 'empty'

In [10]:
ceros_2 = np.empty(10)
ceros_2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Lo mismo podemos hacer con un arreglo lleno de unos.

In [11]:
# Tomamos n = 10.
unos = np.ones(10)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Podemos entender el arreglo de ceros y unos a arreglos de dos dimensiones, es decir, matrices de $n x m$

In [12]:
# Matriz de 7 x 9 llena de ceros.
ceros_matriz = np.zeros((7, 9))
ceros_matriz

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
# Matriz de 6 x 8 llena de unos.
unos_matriz = np.ones((6, 8))
unos_matriz

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

#### Imprimamos de nuevo las matrices pero usando 'print' para omitir la palabra 'array' en la impresión.

In [14]:
print (ceros_matriz)
print ('---------------------------------')
print (unos_matriz)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
---------------------------------
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
print(type(unos))           
print(type(ceros))
print(type(unos_matriz))
print(type(unos_matriz))
print(type(unos[3]))
print(type(unos_matriz[3,3]))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
<class 'numpy.float64'>


#### Podemos crear un arreglo con números entre dos valores cada uno con la misma cantidad de diferencia entre sí.

In [16]:
# 10 Números entre 5 y 50 con la misma cantidad de diferencia entre ellos. 
np.linspace(5, 50, 10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

#### Podemos crear arreglos no sólo con números.

In [17]:
arreglo_2 = np.array( [['x', 'y', 'z'], ['a', 'c', 'e']])
print(arreglo_2)
type(arreglo_2)

[['x' 'y' 'z']
 ['a' 'c' 'e']]


numpy.ndarray

In [18]:
# Usamos 'ndim' para conocer la dimensión del arreglo. 
arreglo_2.ndim

2

#### Usando 'sort' podemos ordenar un arreglo númerico en orden ascendente.

In [19]:
arreglo_num = [12, 4, 10, 40, 2, 5, 97, 63, 82, 73, 35, 28, 83, 19]
np.sort(arreglo_num)

array([ 2,  4,  5, 10, 12, 19, 28, 35, 40, 63, 73, 82, 83, 97])

#### También podemos usar 'sort' en arreglos más complejos.

In [20]:
cabeceras = [ ('nombre', 'S10' ), ('edad', int) ]
datos = [ ('Juan', 10), ('Maria', 70), ('Javier', 42), ('Samuel', 15) ]
usuarios = np.array(datos, dtype = cabeceras)
print('Arreglo original:           ', usuarios)

orden = np.sort(usuarios, order = 'edad' )
print('Arreglo ordenado por edad:  ', orden)

Arreglo original:            [(b'Juan', 10) (b'Maria', 70) (b'Javier', 42) (b'Samuel', 15)]
Arreglo ordenado por edad:   [(b'Juan', 10) (b'Samuel', 15) (b'Javier', 42) (b'Maria', 70)]


#### Con 'arange' podemos crear un arreglo con números naturales según la cantidad que indiquemos.

In [21]:
# Arreglo con 51 números, comenzando en cero.
np.arange(51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [22]:
# Arreglo con números naturales pero en un rango entre 10 y 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [23]:
# Números entre 5 y 51 pero en pasos de 5.
np.arange(5, 51, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

#### Es posible crear arreglos de $n x m$ no sólo con ceros y unos sino que con cualquier número, usando 'full'.

In [24]:
a = np.full( (6, 8), 8)
b = np.full((4, 6), 10)
print(a)
print('----------------------------')
print(b)

[[8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]]
----------------------------
[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


#### Podemos crear matrices diagonales con 'diag'.

In [25]:
np.diag ( [1, 3, 9, 10, 6, 8] )

array([[ 1,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0],
       [ 0,  0,  9,  0,  0,  0],
       [ 0,  0,  0, 10,  0,  0],
       [ 0,  0,  0,  0,  6,  0],
       [ 0,  0,  0,  0,  0,  8]])

#### Construyamos una matriz.

In [26]:
matriz = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

#### Podemos acceder a un valor de la matriz indicando el número de la fila y el número de la columna recordando que la cuenta inicia en cero.

In [27]:
# Fila 3 indicada con 2 y columna 4 indicada con el 3.
matriz[2,3]

14

#### Podemos pasar un arreglo de índices

In [28]:
indices = np.array([1, 2, 3, 3, 4, 5]) # Notar que estamos repitiendo el índice 3.

# Creamos ahora un arreglo con 10 número aleatorios entre 0 y 1:
aleatorio = np.random.random(10)
print ('El vector con números aleatorios es: \n')
print (aleatorio, '\n')

# A cada valor del arreglo con números aleatorios le asignamos un índice:
indices_aleatorio = aleatorio[indices]

print ('El vector con los números de acuerdo a los índices es: \n')
print (indices_aleatorio)

El vector con números aleatorios es: 

[0.05465679 0.75048468 0.49789275 0.1402808  0.5395708  0.6337603
 0.62058706 0.96363246 0.67304009 0.85034454] 

El vector con los números de acuerdo a los índices es: 

[0.75048468 0.49789275 0.1402808  0.1402808  0.5395708  0.6337603 ]


In [29]:
# Probemos con valores booleanos.
indices_2 = np.array([1, 2, 3, 4, 5, 6, 7])
booleano = np.array([True, False, True, False, True, True, False])
print (indices_2[booleano])    # Nos imprimirá aquellos indices con True.

[1 3 5 6]


### Operaciones con Arreglos.

In [30]:
mi_arreglo = np.array([1., 2., 3., 4., 5., 6., 7., 8., 9., 10.])
print ('Multiplicación por si mismo: ', mi_arreglo * mi_arreglo)
print ('Cuadrado del arreglo:        ', mi_arreglo ** 2)
print ('Suma de arreglo con unos:    ', mi_arreglo + np.ones(10))
print ('Resta de arreglo con unos:   ', mi_arreglo - np.ones(10))
print ('División de todo el arreglo: ', mi_arreglo / 2)
print ('División entrada a entrada:  ', mi_arreglo / np.array([2., 4., 1.5, 2., 2.5, 3., 7., 2., 3., 5.]))

Multiplicación por si mismo:  [  1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]
Cuadrado del arreglo:         [  1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]
Suma de arreglo con unos:     [ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
Resta de arreglo con unos:    [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
División de todo el arreglo:  [0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
División entrada a entrada:   [0.5 0.5 2.  2.  2.  2.  1.  4.  3.  2. ]


In [31]:
suma = np.sum(mi_arreglo)
tamaño = len(mi_arreglo)
promedio = suma / tamaño 
promedio_2 = np.average(mi_arreglo)
print ('La suma del arreglo es:                 ', suma)
print ('El tamaño del arreglo es:               ', tamaño)
print ('El promedio usando la suma y tamaño es: ', promedio)
print ('El promedio usando numpy es:            ', promedio_2)

La suma del arreglo es:                  55.0
El tamaño del arreglo es:                10
El promedio usando la suma y tamaño es:  5.5
El promedio usando numpy es:             5.5


### El producto punto.

In [32]:
arreglo1 = np.array([1., 2., 3., 4.])
arreglo2 = np.array([2., 3., 4., 5.])
print (np.sum(arreglo1 * arreglo2))

# Con np.dot podemos calcular el producto interno.
print (np.dot(arreglo1, arreglo2))

40.0
40.0


#### Norma de un vector usando el producto punto.

In [33]:
norma = np.sqrt(np.sum(arreglo1 * arreglo1))
norma2 = np.sqrt(np.dot(arreglo1, arreglo1))
print (norma)
print (norma2)

5.477225575051661
5.477225575051661


#### Podemos hacer el producto entre una matriz y un vector siempre y cuando el número de columnas de la matriz sea igual al número de elementos del vector.

In [34]:
caracteristicas = np.array([[1., 2.], [3., 4.], [5., 6.], [7., 8.]])
print ('Matriz con 2 columnas: \n', caracteristicas)

pesos = np.array([2, 4])
print ('Vector con dos elementos: \n', pesos)

predicion = np.dot(caracteristicas, pesos)
print ('Multiplicación: \n', predicion)

Matriz con 2 columnas: 
 [[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
Vector con dos elementos: 
 [2 4]
Multiplicación: 
 [10. 22. 34. 46.]


### Multipicacion de Matrices.

In [35]:
matriz_1 = np.array([[1., 2., 3.],[4., 5., 6.]])
print ('matriz 1: \n', matriz_1)

matriz_2 = np.array([[1., 2.], [3., 4.], [5., 6.]])
print ('matriz 2: \n', matriz_2)

print ('producto de matrices: \n', np.dot(matriz_1, matriz_2))

matriz 1: 
 [[1. 2. 3.]
 [4. 5. 6.]]
matriz 2: 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
producto de matrices: 
 [[22. 28.]
 [49. 64.]]
